import type {
  Approval,
  AssetPackage,
  Caption,
  OutputFile,
  PackageField,
  PerformanceRecord,
  RenderJob,
  StoryRecord,
  Template,
  User,
} from "./types";

export const users: User[] = [
  {
    id: "user-avery",
    name: "Avery Smith",
    email: "avery@medialab.local",
    role: "producer",
    team: "Media Operations",
    avatar_url: "",
    created_at: "2026-04-24T14:00:00Z",
  },
  {
    id: "user-jordan",
    name: "Jordan Lee",
    email: "jordan@medialab.local",
    role: "approver",
    team: "Comms",
    avatar_url: "",
    created_at: "2026-04-24T14:10:00Z",
  },
];

export const storyRecords: StoryRecord[] = [
  {
    id: "story-spanberger-town-hall",
    title: "Abigail Spanberger Town Hall Quote",
    what_happened:
      "At a packed town hall in Michigan, Rep. Abigail Spanberger made one thing clear: democracy requires leaders willing to defend it.",
    why_it_matters:
      "The moment gives the team a clear, values-forward quote for rapid civic action distribution.",
    primary_messenger: "Abigail Spanberger",
    source_url: "https://example.com/town-hall-video",
    source_type: "Town hall video",
    source_confidence: "verified",
    urgency: "high",
    audience: "Civic action supporters",
    topic: "Democracy",
    series: "Civic Action",
    status: "approved",
    created_by: "user-avery",
    created_at: "2026-04-30T16:42:00Z",
    updated_at: "2026-04-30T17:32:00Z",
  },
  {
    id: "story-medicaid-remarks",
    title: "Medicaid funding remarks",
    what_happened:
      "Rep. Spanberger addressed Medicaid funding cuts and their impact on rural hospitals and patients.",
    why_it_matters:
      "Highlights the local impact of policy decisions on health care access.",
    primary_messenger: "Rep. Abigail Spanberger",
    source_url: "https://example.com/medicaid-remarks",
    source_type: "Official remarks",
    source_confidence: "verified",
    urgency: "high",
    audience: "National and health care advocates",
    topic: "Health Care",
    series: "Health Care Access",
    status: "ready_for_package",
    created_by: "user-avery",
    created_at: "2026-05-01T12:05:00Z",
    updated_at: "2026-05-01T12:08:00Z",
  },
];

export const templates: Template[] = [
  {
    id: "template-quote-card-v2",
    name: "Quote Card V.2",
    version: "2.0.4",
    description: "Highlight a strong quote and package it for fast distribution.",
    template_type: "pack",
    required_fields: [
      "Primary Quote",
      "Speaker Name",
      "Speaker Title",
      "Context Line",
      "Headshot",
    ],
    available_outputs: ["16:9 PNG", "1:1 PNG", "9:16 PNG", "16:9 MP4", "1:1 MP4", "9:16 MP4"],
    motion_ready: true,
    source_file_url: "/mock/source/quote-card-v2.aep",
    thumbnail_url: "",
    status: "active",
    created_at: "2026-04-20T10:00:00Z",
    updated_at: "2026-04-30T10:00:00Z",
    best_for: ["Fast response moments", "Speaker-driven messaging", "Social distribution"],
    performance_tag: "Popular",
  },
  {
    id: "template-stat-card",
    name: "Stat Card",
    version: "1.3.0",
    description: "Present key numbers in a clean, scannable way.",
    template_type: "static",
    required_fields: ["Statistic", "Context", "Source", "Topic"],
    available_outputs: ["16:9 PNG", "1:1 PNG", "9:16 PNG"],
    motion_ready: false,
    source_file_url: "/mock/source/stat-card.fig",
    thumbnail_url: "",
    status: "active",
    created_at: "2026-04-18T10:00:00Z",
    updated_at: "2026-04-29T10:00:00Z",
    best_for: ["Policy numbers", "Proof points", "Clean receipts"],
    performance_tag: "Popular",
  },
  {
    id: "template-contrast-card",
    name: "Contrast Card",
    version: "1.1.0",
    description: "Show the contrast. Make it clear.",
    template_type: "static",
    required_fields: ["Left Position", "Right Position", "Source", "Context", "CTA", "Topic"],
    available_outputs: ["16:9 PNG", "1:1 PNG", "9:16 PNG"],
    motion_ready: true,
    source_file_url: "/mock/source/contrast-card.aep",
    thumbnail_url: "",
    status: "active",
    created_at: "2026-04-18T10:00:00Z",
    updated_at: "2026-04-29T10:00:00Z",
    best_for: ["Policy contrasts", "Vote comparisons", "Issue framing"],
    performance_tag: "Core",
  },
  {
    id: "template-vote-record-card",
    name: "Vote Record Card",
    version: "1.0.0",
    description: "Show the votes. Prove the record.",
    template_type: "static",
    required_fields: ["Bill", "Vote", "Member", "Date", "Impact", "Source", "CTA"],
    available_outputs: ["16:9 PNG", "1:1 PNG", "9:16 PNG"],
    motion_ready: true,
    source_file_url: "/mock/source/vote-record-card.aep",
    thumbnail_url: "",
    status: "active",
    created_at: "2026-04-18T10:00:00Z",
    updated_at: "2026-04-29T10:00:00Z",
    best_for: ["Accountability moments", "Legislative records", "Receipts"],
    performance_tag: "Fast",
  },
  {
    id: "template-what-happened",
    name: "What Happened / Why It Matters",
    version: "1.2.0",
    description: "Explain the what. Deliver the why.",
    template_type: "pack",
    required_fields: ["What Happened", "Why It Matters", "Source", "Messenger", "Audience", "CTA"],
    available_outputs: ["16:9 PNG", "1:1 PNG", "9:16 PNG", "Caption Pack"],
    motion_ready: true,
    source_file_url: "/mock/source/what-happened.aep",
    thumbnail_url: "",
    status: "active",
    created_at: "2026-04-18T10:00:00Z",
    updated_at: "2026-04-29T10:00:00Z",
    best_for: ["Explainers", "Breaking developments", "Message discipline"],
    performance_tag: "Core",
  },
  {
    id: "template-headline-reframe",
    name: "Headline Reframe",
    version: "1.0.0",
    description: "Turn a news hook into a sharp shareable message.",
    template_type: "static",
    required_fields: ["Headline", "Reframe", "Source", "Context"],
    available_outputs: ["16:9 PNG", "1:1 PNG", "9:16 PNG"],
    motion_ready: false,
    source_file_url: "/mock/source/headline-reframe.fig",
    thumbnail_url: "",
    status: "active",
    created_at: "2026-04-19T10:00:00Z",
    updated_at: "2026-04-29T10:00:00Z",
    best_for: ["Rapid response", "News moments", "Message correction"],
    performance_tag: "New",
  },
  {
    id: "template-in-your-state",
    name: "In Your State Card",
    version: "1.0.0",
    description: "Localize a national message by state or district.",
    template_type: "static",
    required_fields: ["State", "Local Stat", "Messenger", "Source", "CTA"],
    available_outputs: ["1:1 PNG", "9:16 PNG"],
    motion_ready: false,
    source_file_url: "/mock/source/in-your-state.fig",
    thumbnail_url: "",
    status: "active",
    created_at: "2026-04-19T10:00:00Z",
    updated_at: "2026-04-29T10:00:00Z",
    best_for: ["Localized campaigns", "State toolkits", "Partner reuse"],
    performance_tag: "Fast",
  },
  {
    id: "template-clip-packaging-pack",
    name: "Clip Packaging Pack",
    version: "1.4.0",
    description: "Turn a clip into a multi-format social set.",
    template_type: "motion",
    required_fields: ["Clip URL", "Speaker", "Hook", "Caption"],
    available_outputs: ["16:9 MP4", "1:1 MP4", "9:16 MP4", "Caption Pack"],
    motion_ready: true,
    source_file_url: "/mock/source/clip-packaging.aep",
    thumbnail_url: "",
    status: "active",
    created_at: "2026-04-17T10:00:00Z",
    updated_at: "2026-04-29T10:00:00Z",
    best_for: ["Town halls", "Floor speeches", "Press clips"],
    performance_tag: "Fast",
  },
];

export const assetPackages: AssetPackage[] = [
  {
    id: "pkg-spanberger-town-hall",
    story_record_id: "story-spanberger-town-hall",
    template_id: "template-quote-card-v2",
    title: "Abigail Spanberger Town Hall Quote",
    status: "approved",
    created_by: "user-avery",
    approval_route: ["editorial", "comms", "final"],
    created_at: "2026-04-30T16:48:00Z",
    updated_at: "2026-04-30T17:32:00Z",
  },
];

export const packageFields: PackageField[] = [
  {
    id: "field-primary-quote",
    asset_package_id: "pkg-spanberger-town-hall",
    field_name: "Primary Quote",
    field_value: "We cannot defend democracy by standing still.",
    field_type: "text",
    required: true,
  },
  {
    id: "field-speaker-name",
    asset_package_id: "pkg-spanberger-town-hall",
    field_name: "Speaker Name",
    field_value: "Abigail Spanberger",
    field_type: "text",
    required: true,
  },
  {
    id: "field-speaker-title",
    asset_package_id: "pkg-spanberger-town-hall",
    field_name: "Speaker Title",
    field_value: "U.S. Representative",
    field_type: "text",
    required: true,
  },
  {
    id: "field-context",
    asset_package_id: "pkg-spanberger-town-hall",
    field_name: "Context Line",
    field_value: "April 2028 Town Hall in Michigan",
    field_type: "text",
    required: true,
  },
  {
    id: "field-headshot",
    asset_package_id: "pkg-spanberger-town-hall",
    field_name: "Headshot",
    field_value: "Portrait attached",
    field_type: "image",
    required: true,
  },
];

export const renderJobs: RenderJob[] = [
  {
    id: "render-spanberger-town-hall",
    asset_package_id: "pkg-spanberger-town-hall",
    template_id: "template-quote-card-v2",
    status: "complete",
    requested_outputs: ["16:9 PNG", "1:1 PNG", "9:16 PNG", "16:9 MP4", "1:1 MP4", "9:16 MP4"],
    started_at: "2026-04-30T16:49:00Z",
    completed_at: "2026-04-30T16:51:00Z",
    error_message: null,
  },
];

export const outputFiles: OutputFile[] = [
  ["16:9 PNG", "image", "PNG", "16:9", "All", "2.3 MB", null],
  ["1:1 PNG", "image", "PNG", "1:1", "Instagram", "1.2 MB", null],
  ["9:16 PNG", "image", "PNG", "9:16", "Stories", "1.4 MB", null],
  ["16:9 MP4", "video", "MP4", "16:9", "YouTube", "12.4 MB", "0:15"],
  ["1:1 MP4", "video", "MP4", "1:1", "Instagram", "10.2 MB", "0:15"],
  ["9:16 MP4", "video", "MP4", "9:16", "TikTok / Reels", "10.8 MB", "0:15"],
  ["Caption Pack ZIP", "zip", "ZIP", "n/a", "All", "5 KB", null],
  ["Source File", "source", "AEP", "n/a", "Archive", "45.7 MB", null],
].map((file, index) => ({
  id: `output-${index + 1}`,
  asset_package_id: "pkg-spanberger-town-hall",
  render_job_id: "render-spanberger-town-hall",
  file_type: file[1] as OutputFile["file_type"],
  format: file[2] ?? "",
  ratio: file[3] ?? "",
  platform: file[4] ?? "",
  file_url: `/mock/outputs/${String(file[0]).toLowerCase().replaceAll(" ", "-")}`,
  file_size: file[5] ?? "",
  duration: file[6],
  created_at: "2026-04-30T16:51:00Z",
}));

const baseCaption =
  "At a packed town hall in Michigan, Rep. Abigail Spanberger made one thing clear:\n\n\"We cannot defend democracy by standing still.\"\n\nWe need leaders who will fight for our rights, our freedoms, and our future.";

export const captions: Caption[] = [
  "x_twitter",
  "instagram",
  "facebook",
  "threads",
  "youtube_community",
  "email_newsletter",
].map((platform, index) => ({
  id: `caption-${platform}`,
  asset_package_id: "pkg-spanberger-town-hall",
  platform: platform as Caption["platform"],
  caption_text:
    index === 0
      ? `${baseCaption}\n\n#Democracy #CivicAction #TownHall`
      : `${baseCaption}\n\n#Democracy #CivicAction #TownHall #2028`,
  alt_text:
    "Quote card graphic with light blue background. Text reads: We cannot defend democracy by standing still. Abigail Spanberger, U.S. Representative. April 2028 Town Hall in Michigan.",
  hashtags: ["#Democracy", "#CivicAction", "#TownHall", "#2028"],
  status: "approved",
  created_at: "2026-04-30T16:52:00Z",
  updated_at: "2026-04-30T17:32:00Z",
}));

export const approvals: Approval[] = [
  {
    id: "approval-editorial",
    asset_package_id: "pkg-spanberger-town-hall",
    reviewer_id: "user-avery",
    review_stage: "editorial",
    status: "approved",
    comment: "Strong line about urgency and values. Good for broad audience.",
    created_at: "2026-04-30T17:00:00Z",
    updated_at: "2026-04-30T17:05:00Z",
  },
  {
    id: "approval-comms",
    asset_package_id: "pkg-spanberger-town-hall",
    reviewer_id: "user-jordan",
    review_stage: "comms",
    status: "approved",
    comment: "Approved for distribution.",
    created_at: "2026-04-30T17:08:00Z",
    updated_at: "2026-04-30T17:32:00Z",
  },
];

export const performanceRecords: PerformanceRecord[] = [
  {
    id: "perf-x",
    asset_package_id: "pkg-spanberger-town-hall",
    platform: "X / Twitter",
    published_url: "https://example.com/post/x",
    impressions: 98600,
    engagements: 4200,
    shares: 1100,
    comments: 418,
    saves: 732,
    downloads: 221,
    engagement_rate: 4.26,
    published_at: "2026-04-30T18:00:00Z",
    created_at: "2026-05-01T11:00:00Z",
  },
];
